ospf:
  process_id: 1
  networks:
    - interface: Ethernet1/1
      area: 0
    - interface: Ethernet1/2
      area: 0
    - interface: loopback0
      area: 0
    - interface: loopback1
      area: 0
bgp:
  asn: 65000
  route_reflector_client: no
  neighbors:
    - remote_ip: 192.168.0.5
      remote_asn: 65000
    - remote_ip: 192.168.0.6
      remote_asn: 65000
pim:
  rp:
    - ip: 192.168.0.5
    - ip: 192.168.0.6
  interfaces:
  - interface: Ethernet1/1
  - interface: Ethernet1/2
  - interface: loopback0