---
- name: Enable OSPF feature
  tags: [api, nxapi, ospf]
  with_items:
    - ospf
  nxos_feature:
    provider:
      host: "{{inventory_hostname}}"
      #transport: nxapi
      timeout: 15
    feature: "{{ item }}"
    state: enabled

- name: Configure OSPF
  tags: [api, nxapi, ospf]
  nxos_ospf:
    provider:
      host: "{{inventory_hostname}}"
      #transport: nxapi
      timeout: 15
    ospf: "{{ ospf.process_id }}"
    state: present

- name: Configure OSPF Interfaces
  tags: [api, nxapi, ospf]
  with_items: "{{ ospf.networks }}"
  nxos_interface_ospf:
    provider:
      host: "{{inventory_hostname}}"
      #transport: nxapi
      timeout: 15
    interface: "{{ item.interface }}"
    ospf: "{{ ospf.process_id }}"
    area: "{{ item.area }}"

- name: CONFIGURE OSPF INTERFACES NETWORK P2P
  nxos_config:
    lines: ip ospf network point-to-point
    parents:
      - 'interface {{ item.interface_type }}{{item.interface_id}}'
    
  with_items: "{{ l3_interfaces }}"